export const ADD_CARD_DECK = "ADD_CARD_DECK"

export const ADD_COST_FILTER = "ADD_COST_FILTER"
export const RMV_COST_FILTER = "RMV_COST_FILTEr"

export const SET_NAME_TEXT = "SET_NAME_TEXT"

export const SET_CARD_DECK = "SET_CARD_DECK"
export const ALL_SET_DECK = "ALL_SET_DECK"

export const RMV_CARD_DECK = "RMV_CARD_DECK";

export const SET_COST_FILTER = "SET_COST_FILTER"

export const SET_DECODE_DECK = "SET_DECODE_DECK"

export const SET_REGION_FILTER = "SET_REGION_FILTER"

export const SET_FILTER_NAME = "SET_FILTER_NAME"